### ISSUE TITLE
Install Additional Dependencies in aoa-r-base

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaExternalDockerImages#1]
Install the following 

- r2pmml
- tdplyr

The tdplyr library is already included in the Dockerfile. However, its not installed. I tried to install it but failed so marking this a as separate ticket.

@dartov @Christian-TD fyi . might take you guys a few minutes.. I failed over the course of 1 hour today to install tdplyr..

**Comment by Christian-TD** [comment]
@willfleury managed to fix it but had to use R version 4.0.3 and it became a big image
