### ISSUE TITLE
Latest R base image not working

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaExternalDockerImages#5]
Plumber and a few other libraries don't appear to be installed correctly.

do 

docker run --rm -it thinkbiganalytics/aoa-r-base:4.0.0 bash

and then try to load plumber.. Also, when using it i see some errors around devtools etc.

![image](https://user-images.githubusercontent.com/10163928/100097921-8699e180-2e5d-11eb-9fc2-5670a163bab7.png)

**Comment by willfleury** [comment]
@Christian-TD fyi. no rush on it as i just used the older image but it seems like sometimes R will fail silently with installing deps

**Comment by Christian-TD** [comment]
Fixed it, had to install some extra packages through apt-get, try now.

**Comment by Christian-TD** [comment]
Fixed
